version: "3.9"

services:
  rdb:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    build: .
    restart: unless-stopped
    command: gunicorn renovation_site.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - rdb
    ports:
      - "8000:8000"
    volumes:
      - .:/app   # optional: for live‑code editing during dev; remove for prod

volumes:
  pg_data: